#!/usr/bin/env python3
"""
Generates VcpFeature static properties from VcpFeatureData.json.
This creates a partial class that can be combined with the core VcpFeature class.
"""

import json
from pathlib import Path

def generate_feature_property(feature):
    """Generate a C# static property for a VCP feature."""
    code = feature['code']
    prop_name = feature['property']
    name = feature['name']
    description = feature['description']
    feature_type = feature['type']
    category = feature['category']
    supports_percentage = 'true' if feature['supportsPercentage'] else 'false'
    aliases = feature.get('aliases', [])
    
    # Generate XML doc comment
    lines = [
        f"    /// <summary>",
        f"    /// {description} (VCP {code})",
        f"    /// </summary>"
    ]
    
    # Generate property
    if aliases:
        aliases_str = ', '.join(f'"{alias}"' for alias in aliases)
        lines.append(f'    public static VcpFeature {prop_name} => new({code}, "{name}", "{description}", VcpFeatureType.{feature_type}, VcpFeatureCategory.{category}, {supports_percentage}, {aliases_str});')
    else:
        lines.append(f'    public static VcpFeature {prop_name} => new({code}, "{name}", "{description}", VcpFeatureType.{feature_type}, VcpFeatureCategory.{category}, {supports_percentage});')
    
    return '\n'.join(lines)

def generate_all_features_list(features):
    """Generate the AllFeatures list."""
    lines = [
        "    /// <summary>",
        "    /// All features registry - contains all predefined MCCS features",
        "    /// </summary>",
        "    public static IReadOnlyList<VcpFeature> AllFeatures { get; } = new List<VcpFeature>",
        "    {"
    ]
    
    for i, feature in enumerate(features):
        comma = ',' if i < len(features) - 1 else ''
        lines.append(f"        {feature['property']}{comma}")
    
    lines.append("    };")
    return '\n'.join(lines)

def main():
    script_dir = Path(__file__).parent
    json_file = script_dir.parent / 'DDCSwitch' / 'VcpFeatureData.json'
    output_file = script_dir.parent / 'DDCSwitch' / 'VcpFeature.Generated.cs'
    
    print(f"Loading {json_file}...")
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    features = data['features']
    print(f"Found {len(features)} features")
    
    # Generate the file
    lines = [
        "// <auto-generated/>",
        "// This file is automatically generated from VcpFeatureData.json",
        "// Do not edit this file directly. Instead, edit VcpFeatureData.json and regenerate.",
        "",
        "namespace DDCSwitch;",
        "",
        "public partial class VcpFeature",
        "{",
        "    // ===== GENERATED VCP FEATURES ====="
    ]
    
    # Group features by category
    categories = {}
    for feature in features:
        category = feature['category']
        if category not in categories:
            categories[category] = []
        categories[category].append(feature)
    
    # Generate properties grouped by category
    for category, category_features in categories.items():
        lines.append("")
        lines.append(f"    // ===== {category.upper()} FEATURES =====")
        lines.append("")
        for feature in category_features:
            lines.append(generate_feature_property(feature))
            lines.append("")
    
    # Generate AllFeatures list
    lines.append("")
    lines.append(generate_all_features_list(features))
    
    lines.append("}")
    lines.append("")
    
    content = '\n'.join(lines)
    
    print(f"Writing to {output_file}...")
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print("Done!")
    print(f"Generated {len(features)} feature properties")

if __name__ == '__main__':
    main()

